routes/admin.php
<?php

namespace App\Http\Controllers\Admin;

use Route;

Route::get('/', ApiController::class . '@edit')->name('admin.index');

// Api routes
Route::get('/api', ApiController::class . '@edit')->name('admin.api.edit');
Route::patch('/api', ApiController::class . '@update')->name('admin.api.update');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

namespace App\Http\Controllers;

use Route;

Route::resource('tournaments', TournamentsController::class);
Route::resource('tournaments.teams.statistics', StatisticsController::class);
Route::resource('users', UsersController::class);

Route::get('/', TournamentsController::class . '@index')->name('home');
Route::get('/home', TournamentsController::class . '@index');

// Authentication Routes...
Route::get('login', Auth\LoginController::class . '@showLoginForm')->name('login');
Route::post('login', Auth\LoginController::class . '@login');
Route::post('logout', Auth\LoginController::class . '@logout')->name('logout');

// Registration Routes...
Route::get('register', Auth\RegisterController::class . '@showRegistrationForm')->name('register');
Route::post('register', Auth\RegisterController::class . '@register');

// Password Reset Routes...
Route::get('password/reset', Auth\ForgotPasswordController::class . '@showLinkRequestForm')->name('password.request');
Route::post('password/email', Auth\ForgotPasswordController::class . '@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', Auth\ResetPasswordController::class . '@showResetForm')->name('password.reset');
Route::post('password/reset', Auth\ResetPasswordController::class . '@reset');

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use DateTimeInterface;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'is_admin' => 'bool',
    ];

    /**
     * @param DateTimeInterface $date
     *
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format(Carbon::ATOM);
    }

}

app/Http/Controllers/Admin/ApiController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApiController extends Controller
{
    public function edit()
    {
        return view('admin.api');
    }

    public function update(Request $request)
    {
        $values = array_dot($request->only('esports'));

        foreach ($values as $key => $value) {
            DB::table('config')->updateOrInsert(compact('key'), compact('key', 'value'));
        }

        return redirect()
            ->route('admin.api.edit')
            ->with('success_message', 'Settings updated successfully!');
    }
}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response|string
     */
    public function index(Request $request)
    {
        return User::paginate($request->get('limit', 10))->all();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response|string
     */
    public function show(User $user)
    {
        return $user;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StatisticsController.php
<?php

namespace App\Http\Controllers;

use App\Services\StatisticsService;
use Illuminate\Http\Request;

class StatisticsController extends Controller
{
    public function index($tournament, $team, StatisticsService $service)
    {
        $team = $service->tournamentTeam($tournament, $team);

        return view('statistics.index', compact('team'));
    }
}

app/Http/Controllers/TournamentsController.php
<?php

namespace App\Http\Controllers;

use ESportsClient\Client;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;

class TournamentsController extends Controller
{
    public function index(Client $client, Guard $auth, Request $request)
    {
        $limit = 10;
        $page = $auth->check() ? $request->get('page', 1) : 1;
        $tournaments = $client->tournamentList($page);

        return view('tournaments.index', compact('tournaments', 'page', 'limit'));
    }

    public function show($id, Client $client)
    {
        $tournament = $client->tournament($id);

        return view('tournaments.show', compact('tournament'));
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateProfileRequest;
use App\Models\User;
use Illuminate\Contracts\Hashing\Hasher;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    public function update(UpdateProfileRequest $request, Hasher $hash)
    {
        /** @var User $user */
        $user = auth()->user();

        $user->name = $request->name;
        $user->password = bcrypt($request->new_password);
        $user->save();

        return redirect()
            ->route('users.edit', $user->id)
            ->with('success_message', 'Profile updated successfully!');
    }
}

resources/views/admin/api.blade.php
@extends('layouts.admin')

@section('content')
    @parent

    <div class="container">
        <h1>API settings</h1>
        <form action="{{route('admin.api.update')}}" method="post">
            {{csrf_field()}}
            {{method_field('PATCH')}}
            <label class="checkbox">
                <checkbox name="esports[enabled]"
                          label="Enabled"
                          :checked="{{ old('esports.enabled', config('esports.enabled')) ? 'true' : 'false' }}"></checkbox>
            </label>
            <inputfield name="esports[base_uri]"
                        label="Base URI"
                        value="{{old('esports.base_uri', config('esports.base_uri'))}}"></inputfield>
            <inputfield
                    label="Credentials"
                    name="esports[credentials]"
                    value="{{old('esports.credentials', config('esports.credentials'))}}"></inputfield>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <ul class="nav nav-pills">
            <li class="{{in_array(Route::current()->getName(), ['admin.index', 'admin.api.edit']) ? 'active' : ''}}">
                <a href="{{route('admin.api.edit')}}">API</a>
            </li>
        </ul>
    </div>
@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        @can('admin')
                            <li>
                                <a href="{{route('admin.index')}}" title="Admin panel">
                                    <span class="glyphicon glyphicon-wrench"></span>
                                </a>
                            </li>
                        @endcan
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{route('users.edit', auth()->user()->id)}}">
                                        Update profile
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if(Session::has('success_message'))
        <div class="container">
            <div class="alert alert-success">{{Session::get('success_message')}}</div>
        </div>
    @endif

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/statistics/index.blade.php
<?php /** @var $team \ESportsClient\Result\Team */ ?>
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{$team->name}} statistics</h1>
        @foreach($team->players as $player)
            <div>
                <h3>{{$player->name}}</h3>
                @if($player->statistics)
                    <statistic v-bind="{{json_encode($player->statistics)}}"></statistic>
                @else
                    <span class="label label-default">Unknown</span>
                @endif
            </div>
        @endforeach
    </div>
@stop

resources/views/tournaments/index.blade.php
<?php /** @var $tournaments \ESportsClient\Result\Tournament[] */ ?>
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>@lang('app.tournament-list')</h1>
        <div class="list-group">
            @foreach($tournaments as $tournament)
                <a class="list-group-item" href="{{route('tournaments.show', $tournament->id)}}">
                    <span class="badge" title="@lang('app.tournament-team-count')">
                        {{$tournament->teams ? count($tournament->teams) : 0}}
                    </span>
                    <h4 class="list-group-item-heading">
                        {{$tournament->name}}
                    </h4>
                    @if($tournament->startsAt)
                        <p class="list-group-item-text">
                            {{$tournament->startsAt->format('Y-m-d')}}
                        </p>
                    @endif
                </a>
            @endforeach
        </div>
        @if(Auth::check())
            <nav aria-label="...">
                <ul class="pager">
                    @if($page > 1)
                        <li class="previous">
                            <a href="{{route('tournaments.index', ['page' => $page-1])}}">
                                <span aria-hidden="true">&larr;</span>
                                Older
                            </a>
                        </li>
                    @endif
                    @if(count($tournaments) === $limit)
                        <li class="next">
                            <a href="{{route('tournaments.index', ['page' => $page+1])}}">
                                Newer
                                <span aria-hidden="true">&rarr;</span>
                            </a>
                        </li>
                    @endif
                </ul>
            </nav>
        @endif
    </div>
@stop

resources/views/tournaments/show.blade.php
<?php /** @var \ESportsClient\Result\Tournament $tournament */ ?>
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>{{$tournament->name}}</h1>
        @if($tournament->startsAt)
            <p>
                <strong>Starts at:</strong>
                {{$tournament->startsAt->format('Y-m-d H:i:s')}}
            </p>
        @endif
        @if($tournament->endsAt)
            <p>
                <strong>Ends at:</strong>
                {{$tournament->endsAt->format('Y-m-d H:i:s')}}
            </p>
        @endif

        @if($tournament->teams)
            <h2>Teams</h2>
            <ul class="list-group">
                @foreach($tournament->teams as $team)
                    <li class="list-group-item">
                        @if(Auth::check())
                            <a class="pull-right"
                               title="Team tournament statistics"
                               href="{{route('tournaments.teams.statistics.index', [$tournament->id, $team->id])}}">
                                <span class="glyphicon glyphicon-stats"></span>
                            </a>
                        @endif
                        {{$team->name}}
                    </li>
                @endforeach
            </ul>
        @endif
    </div>
@stop

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="{{route('users.update', $user->id)}}" method="post">
            {{csrf_field()}}
            {{method_field('PATCH')}}
            <h1>{{$user->name}}</h1>
            <inputfield name="name"
                        label="Name"
                        value="{{old('name', $user->name)}}"
                        :errors="{{json_encode($errors->get('name'))}}"></inputfield>
            <h2>Change password</h2>
            <inputfield type="password"
                        name="current_password"
                        label="Current password"
                        :errors="{{json_encode($errors->get('current_password'))}}"></inputfield>
            <inputfield type="password"
                        name="new_password"
                        label="New password"
                        :errors="{{json_encode($errors->get('new_password'))}}"></inputfield>
            <inputfield type="password"
                        name="new_password_confirmation"
                        label="Repeat password"
                        :errors="{{json_encode($errors->get('new_password_confirmation'))}}"></inputfield>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
@stop